CREATE TABLE SQL901.MARKET_DATA (
crypto_name VARCHAR2(50),
symbol VARCHAR2(10),
crypto_rank INT,
price NUMERIC,
oneday FLOAT,
oneweek FLOAT,
marketcapital NUMERIC,
crypto_volume NUMERIC,
circulationsupply NUMERIC,
cryptosymbol NUMERIC,
fullmarketcap NUMERIC,
maxsupply NUMERIC,
onedaylow NUMERIC,
onedayhigh NUMERIC,
volumemarketcap FLOAT,
marketdominance FLOAT,
roi_onemonth FLOAT,
pricechange NUMERIC
);